title: CS4850-DL1
description: >- # this means to ignore newlines until "baseurl:"
  Quantum Computing Research Capstone project for CS4850
baseurl: "/CS4850-DL1/" # the subpath of your site, e.g. /blog
url: "https://ksu-quantum-capstone.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ethanbtlr

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
